
package me.hengwei.t.tutorial.javaee;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.11-b150120.1832
 * Generated source version: 2.2
 * 
 */
@WebService(name = "HelloWebService", targetNamespace = "http://javaee.tutorial.t.hengwei.me/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface HelloWebService {


    /**
     * 
     */
    @WebMethod(operationName = "HelloWebService")
    @RequestWrapper(localName = "HelloWebService", targetNamespace = "http://javaee.tutorial.t.hengwei.me/", className = "me.hengwei.t.tutorial.javaee.HelloWebService_Type")
    @ResponseWrapper(localName = "HelloWebServiceResponse", targetNamespace = "http://javaee.tutorial.t.hengwei.me/", className = "me.hengwei.t.tutorial.javaee.HelloWebServiceResponse")
    @Action(input = "http://javaee.tutorial.t.hengwei.me/HelloWebService/HelloWebServiceRequest", output = "http://javaee.tutorial.t.hengwei.me/HelloWebService/HelloWebServiceResponse")
    public void helloWebService();

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sayHello", targetNamespace = "http://javaee.tutorial.t.hengwei.me/", className = "me.hengwei.t.tutorial.javaee.SayHello")
    @ResponseWrapper(localName = "sayHelloResponse", targetNamespace = "http://javaee.tutorial.t.hengwei.me/", className = "me.hengwei.t.tutorial.javaee.SayHelloResponse")
    @Action(input = "http://javaee.tutorial.t.hengwei.me/HelloWebService/sayHelloRequest", output = "http://javaee.tutorial.t.hengwei.me/HelloWebService/sayHelloResponse")
    public String sayHello(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
